import type { Metadata } from 'next';
import { Avatar } from '@base-ui/react/avatar';
import { Button } from '@base-ui/react/button';
import { Geist, Geist_Mono } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { DEMO_ACCESS_TOKEN_COOKIE, parseUsernameFromDemoJwt } from '@/lib/demo-auth';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get(DEMO_ACCESS_TOKEN_COOKIE)?.value;
  const username = parseUsernameFromDemoJwt(token) ?? '';
  const isAuthenticated = Boolean(username);
  const userInitials = username
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((chunk) => chunk.charAt(0).toUpperCase())
    .join('');

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {isAuthenticated ? (
          <header className="sticky top-0 z-20 border-b border-zinc-200 bg-white/95 backdrop-blur">
            <div className="mx-auto flex w-full max-w-5xl items-center justify-between px-6 py-3">
              <div className="flex items-center gap-3">
                <Avatar.Root className="inline-flex size-9 items-center justify-center overflow-hidden rounded-full bg-zinc-100 text-sm font-semibold text-zinc-700">
                  <Avatar.Image
                    src="https://i.pravatar.cc/72?img=32"
                    width={36}
                    height={36}
                    className="size-full object-cover"
                  />
                  <Avatar.Fallback delay={500}>{userInitials || 'US'}</Avatar.Fallback>
                </Avatar.Root>
                <span className="text-sm font-medium text-color-text-default">{username}</span>
              </div>
              <div className="flex items-center gap-3">
                <Link
                  href="/settings"
                  className="text-sm font-medium text-color-text-brand underline underline-offset-4 hover:opacity-80"
                >
                  Settings
                </Link>
                <form action="/api/mock-logout" method="post">
                  <Button
                    type="submit"
                    className="inline-flex h-8 items-center justify-center rounded-md border border-zinc-300 px-3 text-xs font-medium text-zinc-700 hover:bg-zinc-100"
                  >
                    Salir
                  </Button>
                </form>
              </div>
            </div>
          </header>
        ) : null}
        {children}
      </body>
    </html>
  );
}
